/*
Question #1: 
If we exclude the discounts that have been given, the expected profit margin for each product is calculated by: (retail price - cost) / retail price. 

Create a column that flags products with a name that includes “Vintage” as products from Nike Vintage and Nike Official otherwise. 

Calculate the expected profit margins for each product name and include the group that splits products between Nike Official and Nike Vintage in the result.
*/
SELECT
    p.product_name,
    (p.retail_price - p.cost) / p.retail_price as profit_margin,
    CASE
        WHEN p.product_name LIKE 'Vintage%' THEN 'Nike Vintage'
        ELSE 'Nike Official'
    END AS Business_unit
FROM products p
GROUP BY p.product_name, profit_margin
;


/*
Question #2: 
What is the profit margin for each distribution center? Are there any centers that stand out?
*/

SELECT
    dc.name as distribution_center_name,
    AVG((p.retail_price - p.cost) / p.retail_price) as profit_margin
FROM products p
JOIN 
   order_items oi ON oi.product_id = p.product_id
JOIN
   orders o ON oi.order_id = o.order_id
JOIN
   distribution_centers dc ON p.distribution_center_id = dc.distribution_center_id
GROUP BY dc.name;



/*
Question #3: 
The real profit margin per order item is calculated by: (sales price - cost) / sales price. By summing up all the order items, we will find the real profit margin generated by the products.

Calculate the profit margin for the Nike Official products: Nike Pro Tights, Nike Dri-FIT Shorts, and Nike Legend Tee
*/

SELECT
    p.product_name,
    SUM(oi.sale_price - p.cost) / SUM(oi.sale_price) as profit_margin
FROM products p
JOIN 
   order_items oi ON oi.product_id = p.product_id
WHERE p.product_name IN ('Nike Pro Tights', 'Nike Dri-FIT Shorts', 'Nike Legend Tee')
GROUP BY p.product_name
;


/*
Question #4: 
Calculate the real profit margin by product and split the data using the created date before 2021-05-01 and post 2021-05-01 for Nike Official order items.
*/


SELECT
    p.product_name,
    SUM(oi.sale_price - p.cost) / SUM(oi.sale_price) as profit_margin,
    CASE
       WHEN oi.created_at < '2021-05-01' THEN 'Pre-May'
       ELSE 'Post-May'
    END AS may21_split
FROM products p
JOIN 
   order_items oi ON oi.product_id = p.product_id
GROUP BY p.product_name, may21_split
;


/*
Question #5: 
Calculate the profit margin by product for both Nike Official and Nike Vintage products in a single view 
*/

SELECT
    p.product_name,
    SUM(oi.sale_price - p.cost) / SUM(oi.sale_price) as profit_margin
FROM products p
JOIN 
   order_items oi ON oi.product_id = p.product_id
GROUP BY p.product_name
UNION
SELECT
    p.product_name,
    SUM(oiv.sale_price - p.cost) / SUM(oiv.sale_price) as profit_margin
FROM products p
JOIN 
    order_items_vintage oiv on oiv.product_id = p.product_id
GROUP BY p.product_name
;


/*
Question #6: 
What are the top 10 products by profit margin from Nike Official and Nike Vintage? 
Include the product name, profit margin, and what business unit (Nike Official or Nike Vintage) sells the product.
*/

SELECT
    p.product_name,
    SUM(oi.sale_price - p.cost) / SUM(oi.sale_price) as profit_margin,
    CASE 
       WHEN p.product_name LIKE 'Vintage%' THEN 'Nike Vintage'
       ELSE 'Nike Official'
    END AS Business_Unit
FROM products p
JOIN 
   order_items oi ON oi.product_id = p.product_id
GROUP BY p.product_name, Business_Unit
UNION
SELECT
    p.product_name,
    SUM(oiv.sale_price - p.cost) / SUM(oiv.sale_price) as profit_margin,
    CASE 
        WHEN p.product_name LIKE 'Vintage%' THEN 'Nike Vintage'
        ELSE 'Nike Official'
    END AS Business_Unit
FROM products p
JOIN 
    order_items_vintage oiv on oiv.product_id = p.product_id
GROUP BY p.product_name, Business_Unit
ORDER by profit_margin desc limit 10
;



